spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

openai.api.key=${OPENAI_API_KEY}
gemini.api.key=${GEMINI_API_KEY}

aws.region=us-east-2
aws.s3.bucket-name=${S3_ALURA_CHALANGE}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}

server.error.include-stacktrace=never
